config/routes.rb
Rails.application.routes.draw do

  resources :settings, only: [:new, :edit,:update,:create]
  get 'messages/:target_id'  => "messages#new", as: 'new_message'

  post 'messages/send_mail'  => "messages#send_mail", as: 'send_message'

  root to: "orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "user/sessions" }, skip: [:registration, :password]
  resources :restaurants
  resources :favorites
  resources :orders do
    resources :order_positions
    get 'messages/:target_id'  => "messages#new", as: 'new_message_order'
  end
  get 'debts' => 'debts#index'
  get 'debts/:id' => 'debts#edit', as: 'edit_debts'
  patch 'debts/:id' => 'debts#update', as: 'update_debts'

end

app/models/order_position.rb
class OrderPosition < ActiveRecord::Base
  validates :name, length: { minimum: 4 }
  validates :cost, presence: true, numericality: { greater_than: 0 }
  belongs_to :order
  belongs_to :user
end

app/controllers/order_positions_controller.rb
class OrderPositionsController < ApplicationController
  before_action :set_order_position, only: [:show, :edit, :update, :destroy]

  # GET /order_positions
  # GET /order_positions.json
  def index
    @order_positions = Order.find(params[:order_id]).order_positions
  end

  # GET /order_positions/1
  # GET /order_positions/1.json
  def show
  end

  # GET /order_positions/new
  def new
    @order = Order.find(params[:order_id])
    if @order.status != 'nowe'
      redirect_to @order, notice: 'Możesz dodawać pozycje tylko do zamówień o statusie nowe'
    end
    @order_position = OrderPosition.new
  end

  # GET /order_positions/1/edit
  def edit
    @order = Order.find(params[:order_id])
    if @order.status != 'nowe'
      redirect_to @order, notice: 'Możesz edytować pozycje tylko do zamówień o statusie nowe'
    end
    @order_position = OrderPosition.find(params[:id])
  end

  # POST /order_positions
  # POST /order_positions.json
  def create
    @order_position = OrderPosition.new(order_position_params)
    @order = Order.find(params[:order_id])
    if @order.status != 'nowe'
      redirect_to @order, notice: 'Możesz dodawać pozycje tylko do zamówień o statusie nowe'
    end
    @order_position.order = @order
    @order_position.user = current_user
    respond_to do |format|
      if @order_position.save
        format.html { redirect_to @order, notice: 'Pomyślnie dodano pozycję do zamówienia.' }
        format.json { render :show, status: :created, location: @order_position }
      else
        format.html { render :new }
        format.json { render json: @order_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_positions/1
  # PATCH/PUT /order_positions/1.json
  def update
    @order = Order.find(params[:order_id])
    if @order.status != 'nowe'
      redirect_to @order, notice: 'Możesz dodawać pozycje tylko do zamówień o statusie nowe'
    end
    respond_to do |format|
      if @order_position.update(order_position_params)
        format.html { redirect_to @order, notice: 'Pozycja pomyślnie edytowana.' }
        format.json { render :show, status: :ok, location: @order_position }
      else
        format.html { render :edit }
        format.json { render json: @order_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_positions/1
  # DELETE /order_positions/1.json
  def destroy
    @order = Order.find(params[:order_id])
    if @order.status != 'nowe'
      redirect_to @order, notice: 'Możesz usuwać pozycje tylko z zamówień o statusie nowe'
    end
    @order_position.destroy
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Order position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_position
      @order_position = OrderPosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_position_params
      params.require(:order_position).permit(:name, :cost)
    end
end

app/helpers/order_positions_helper.rb
module OrderPositionsHelper
end

app/views/order_positions/_form.html.erb
<%= form_for([@order, @order_position]) do |f| %>
  <% if @order_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_position.errors.count, "error") %> coś poszło nie tak:</h2>

      <ul>
      <% @order_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Treść pozycji" %><br>
    <%= f.text_area :name, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :Koszt %><br>
    <%= f.number_field :cost, class: "form-control", pattern: '(\d{3})([\.])(\d{2})', min: 0.01, max: 1000.00, step: 0.01 %>
  </div>
  <div class="actions">
    <%= f.submit "Dodaj pozycję do zamówienia", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/order_positions/edit.html.erb
<h1>Edytuj</h1>

<%= render 'form' %>

<%= link_to 'Powrót', @order %>

app/views/order_positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Positions</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>User</th>
      <th>Name</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_positions.each do |order_position| %>
      <tr>
        <td><%= order_position.order %></td>
        <td><%= order_position.user %></td>
        <td><%= order_position.name %></td>
        <td><%= order_position.cost %></td>
        <td><%= link_to 'Show', order_position %></td>
        <td><%= link_to 'Edit', edit_order_position_path(order_position) %></td>
        <td><%= link_to 'Destroy', order_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order position', new_order_order_position_path %>

app/views/order_positions/new.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Nowa pozycja do zamówienia</h1>

<div class="alert alert-dismissable alert-warning">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Pamiętaj!</h4>
  <p>Przed stworzeniem pozcji zamówienia przeczytaj opis osoby zamawiającej!</p>
  </br>
  <p><strong>Opis</strong></p>
  <p><%= @order.desctiption %></p>
</div>

<%= render 'form' %>


<h4>Wcześniej z tej restauracji zamawiałeś:</h4>


<div class="list-group">
  <% current_user.order_positions.order(created_at: :desc).each do |position| %>
      <% if position.order.restaurant == @order.restaurant %>
          <div class="list-group-item">
            <%= text_field_tag 'nazwa', position.name %>
            <%= text_field_tag 'koszt', position.cost %> zl
          </div>
      <% end %>
  <% end %>
</div>

<h4>Inni dzisiaj zamówili:</h4>


<div class="list-group">
  <% @order.order_positions.order(created_at: :desc).each do |position| %>
      <% if position.user != current_user %>
          <div class="list-group-item">
            <%= text_field_tag 'nazwa', position.name %>
            <%= text_field_tag 'koszt', position.cost %> zl
            <%= position.user.name %>
          </div>
      <% end %>
  <% end %>
</div>
<%= link_to 'Powrót', order_path(@order) %>

app/views/order_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_position.order %>
</p>

<p>
  <strong>User:</strong>
  <%= @order_position.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @order_position.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order_position.cost %>
</p>

<%= link_to 'Edit', edit_order_position_path(@order_position) %> |
<%= link_to 'Back', order_positions_path %>