config/routes.rb
Rails.application.routes.draw do

  resources :settings, only: [:new, :edit,:update,:create]
  get 'messages/:target_id'  => "messages#new", as: 'new_message'

  post 'messages/send_mail'  => "messages#send_mail", as: 'send_message'

  root to: "orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "user/sessions" }, skip: [:registration, :password]
  resources :restaurants
  resources :favorites
  resources :orders do
    resources :order_positions
    get 'messages/:target_id'  => "messages#new", as: 'new_message_order'
  end
  get 'debts' => 'debts#index'
  get 'debts/:id' => 'debts#edit', as: 'edit_debts'
  patch 'debts/:id' => 'debts#update', as: 'update_debts'

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  has_many :order_positions
  enum status: {
		nowe: 1,
		zamowione: 2,
		dostarczone: 3,
    anulowane: 4
		}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where('ordertime > ?', DateTime.now.beginning_of_day).all
  end

  def today
    @orders = Order.where("ordertime >= #{Date.today}")
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    if @order.user != current_user
      redirect_to @order, notice: 'Nie jesteś autorem zamówienia'
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = "nowe"
    respond_to do |format|
      if @order.save
        Favorite.where(restaurant_id: @order.restaurant.id).where.not(user_id: current_user.id).each do |favorite|
          UserNotifier.favorite_restaurant_order(favorite.user, @order).deliver_now
        end
        Setting.where.not(user: current_user).where(mailing: 1).each do |setting|
          UserNotifier.favorite_restaurant_order(setting.user, @order).deliver_now
        end
        format.html { redirect_to @order, notice: 'Zamówienie zostało założone.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.user != current_user
      redirect_to @order, notice: 'Nie jesteś autorem zamówienia'
    end
    puts '--------'
    p order_params
    puts '--------'
    
    @order.restaurant_id = order_params[:restaurant_id]
    @order.ordertime = DateTime.civil_from_format(
        :local,
        order_params["ordertime(1i)"].to_i,
        order_params["ordertime(2i)"].to_i,
        order_params["ordertime(3i)"].to_i,
        order_params["ordertime(4i)"].to_i,
        order_params["ordertime(5i)"].to_i
    )
    @order.desctiption = order_params[:desctiption]
    @order.status = order_params[:status]
    if @order.valid? and @order.status_changed?
      @order.order_positions.each do |position|
        if position.user != @order.user
          UserNotifier.order_status_change(position.user, @order).deliver_now
        end
      end
    end
    respond_to do |format|
      if @order.save
        if @order.status_changed?
          @order.order_positions.each do |position|
            UserNotifier.order_status_change(position.user, @order).deliver_now
          end
        end
        format.html { redirect_to @order, notice: 'Pomyślnie edytowałeś zamówienie' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    if @order.user != current_user
      redirect_to @order, notice: 'Nie jesteś autorem zamówienia'
    end
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :restaurant_id, :ordertime, :desctiption, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Restauracja" %><br>
    <%= f.select(:restaurant_id, Restaurant.all.map { |e| [e.name, e.id] }, {}, {:class => "form-control"}) %>
  </div>
  <div class="field">
    <%= f.label "Czas zamówienia" %><br>
    <%= f.datetime_select :ordertime %>
  </div>
  <div class="field">
    <%= f.label "Opis" %><br>
    <%= f.text_area :desctiption, class: "form-control floating-label", placeholder: "Tutaj napisz np czy chcesz kase do ręki" %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(Order.statuses.map { |k,v| [k.humanize, k] }, :selected => @order.status), {}, {:class => "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit "Wyślij", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div class="col-md-4">
  <div class="panel panel-default">
    <%= link_to(order) do %>
    <div class="panel-heading"><h4>Restauracja: <%= order.restaurant.name %> <span class="label label-danger"><%= order.status %></span></h4></div>
    <% end %>
    <div class="panel-body">
      <p>Założyciel: <%= order.user.name %></p>
      <% if !order.ordertime.nil? %>
          <p>Termin: <%= order.ordertime.strftime('%F') %> o godzinie <%= order.ordertime.strftime('%H:%M') %></p>
      <% end %>
      <%= link_to order.restaurant.link, order.restaurant.link, :target => "_blank"  %>
      <% if order.user == current_user  %>
          <p><%= link_to 'Edytuj', edit_order_path(order), class: "btn btn-primary" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="page-header">
	<h1>Edytuj zamówienie</h1>
</div>
<%= render 'form' %>

<%= link_to 'Pokaż', @order %> |
<%= link_to 'Wstecz', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
	<h1>Zamówienia</h1>
</div>

<div class="row">
  <%= render @orders %>
</div>
<br>

<%= link_to '', new_order_path, class: "btn btn-danger btn-fab btn-raised mdi-content-add" %>

app/views/orders/new.html.erb
<h1>Nowe zamowienie</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Restauracja: <%= @order.restaurant.name %> <span class="label label-danger"><%= @order.status %></span></h4>
      <div class="buttons pull-right">
        <% if @order.status == 'nowe' %>
              <%= link_to '', new_order_order_position_path(@order), class: "btn btn-danger btn-fab btn-raised mdi-content-add" %>
        <% end %>
        <% if @order.user == current_user%>
              <%= link_to '', edit_order_path(@order), class: "btn btn-primary btn-fab btn-raised mdi-content-create" %>
        <% end %>
      </div>
  </div>
  <div class="panel-body">
    <p>
      <strong>Zamawiający</strong>
      <%= @order.user.name %>
    </p>

    <p>
      <% if !@order.ordertime.nil? %>
          <strong>Termin</strong>
          <%= @order.ordertime.strftime('%F') %> o godzinie <%= @order.ordertime.strftime('%H:%M') %>
      <% end %>
    </p>

    <p>
      <strong>Opis</strong>
      <%= @order.desctiption %>
    </p>

    <p>
      <%= link_to @order.restaurant.link, @order.restaurant.link, :target => "_blank"  %>
    </p>

    <b>Łączna suma zamówień: <%= number_to_currency(@order.order_positions.sum(:cost), locale: :pl) %></b>
  </div>
</div>

    <div class="page-header">
      <h4>Pozycje zamówienia</h4>
    </div>
    <div class="list-group">
      <% @order.order_positions.each do |order_position| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="pull-left">
                  <p><strong><%= order_position.name %></strong></p>
                  <p><%= order_position.user.name %></p>
              </div>
              <div class="buttons-poz pull-right">
                  <% if order_position.user == current_user and @order.status == 'nowe' %>
                      <%= link_to '', edit_order_order_position_path(@order, order_position), class: "btn btn-primary btn-fab btn-raised mdi-content-create" %>
                      <%= link_to '', order_order_position_path(@order, order_position), method: :delete, data: { confirm: 'Czy na pewno usunąć?' }, class: "btn btn-danger btn-fab btn-raised mdi-content-remove" %>
                  <% end %>
                  <%= link_to '', order_new_message_order_path(@order, order_position.user), class: "btn btn-info btn-fab btn-raised mdi-content-mail" %>
              </div>
            </div>
            <div class="panel-footer"><%= number_to_currency(order_position.cost, locale: :pl)  %></div>
          </div>
      <% end %>
    </div>

    <b>Łączna suma zamówień: <%= number_to_currency(@order.order_positions.sum(:cost), locale: :pl) %></b>

    <br>

    <%= link_to 'Powrót', orders_path %>