config/routes.rb
Rails.application.routes.draw do

  resources :settings, only: [:new, :edit,:update,:create]
  get 'messages/:target_id'  => "messages#new", as: 'new_message'

  post 'messages/send_mail'  => "messages#send_mail", as: 'send_message'

  root to: "orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "user/sessions" }, skip: [:registration, :password]
  resources :restaurants
  resources :favorites
  resources :orders do
    resources :order_positions
    get 'messages/:target_id'  => "messages#new", as: 'new_message_order'
  end
  get 'debts' => 'debts#index'
  get 'debts/:id' => 'debts#edit', as: 'edit_debts'
  patch 'debts/:id' => 'debts#update', as: 'update_debts'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, length: { in: 4..100 }
	validates :link, length: { in: 4..300 }

	has_many :favorites
	has_many :orders
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :link, :description)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nazwa" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Link" %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Opis" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz restaurację", class: "btn btn-default" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edycja restauracji: <%= @restaurant.name %></h1>

<%= render 'form' %>

<%= link_to 'Szczegóły', @restaurant %> |
<%= link_to 'Powrót', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dodane restauracje</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Link</th>
      <th>Opis</th>
      <th>Szczegóły</th>
      <th>Edycja</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.link %></td>
        <td><%= restaurant.description %></td>
        <td><%= link_to 'Szczegóły', restaurant %></td>
        <td><%= link_to 'Edytuj', edit_restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '', new_restaurant_path, class: "btn btn-danger btn-fab btn-raised mdi-content-add" %>

app/views/restaurants/new.html.erb
<h1>Nowa restauracja</h1>

<%= render 'form' %>

<%= link_to 'Powrót', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
<h1>
<p>
  <strong>Nazwa:</strong>
  <%= @restaurant.name %>
</p>
</h1>
</div>

<p>
  <strong>Link:</strong>
  <%= @restaurant.link %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @restaurant.description %>
</p>

<%= link_to 'Educja', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Powrót', restaurants_path %>