config/routes.rb
Rails.application.routes.draw do

  resources :settings, only: [:new, :edit,:update,:create]
  get 'messages/:target_id'  => "messages#new", as: 'new_message'

  post 'messages/send_mail'  => "messages#send_mail", as: 'send_message'

  root to: "orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "user/sessions" }, skip: [:registration, :password]
  resources :restaurants
  resources :favorites
  resources :orders do
    resources :order_positions
    get 'messages/:target_id'  => "messages#new", as: 'new_message_order'
  end
  get 'debts' => 'debts#index'
  get 'debts/:id' => 'debts#edit', as: 'edit_debts'
  patch 'debts/:id' => 'debts#update', as: 'update_debts'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Senteobiady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="google-signin-client_id" content="22688400082-lun2f3ujo0oi9pg4sc4ntgtie9hp5h53.apps.googleusercontent.com">
</head>
<body>

<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Sente obiady', orders_path, class: "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Zamówienia', orders_path %></li>
              <!-- <li><a href="#">Dzisiejsze</a></li> -->
              <li><%= link_to 'Restauracje', restaurants_path %></li>
              <!-- <li><a href="#">Moje zamówienia</a></li> -->
              <li><%= link_to 'Ulubione', favorites_path %></li>
              <li><%= link_to 'Należności', debts_path %></li>
              <li><%= link_to 'Ustawienia', new_setting_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
	            <div id="loggeduser">
	              <% if current_user %>
	              	Jesteś zalogowany jako <b><%= current_user.name %></b>
	              	(<%= link_to "Wyloguj", destroy_user_session_path, method: :delete, class: 'text-danger'  %>)
	              <% end %>
              </div>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <%= yield %>

    </div> <!-- /container -->

</body>
</html>

app/views/layouts/blank.html.erb
<html>
<head>
  <title>Senteobiady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container container1">
      <!-- Main component for a primary marketing message or call to action -->
      <%= yield %>
</div> <!-- /container -->

</body>
</html>